### ISSUE TITLE
_getPredictedBuffer和_getBufferSpeed

### ISSUE THREAD

**Issue by wangynustc** [KwaiVideoTeam/las#1]
https://github.com/KwaiVideoTeam/las/blob/33335b219067dd99fda31014868d1ea8a9e2d061/client/las.js/src/abr/abr-algorithm-simple.ts#L243

https://github.com/KwaiVideoTeam/las/blob/33335b219067dd99fda31014868d1ea8a9e2d061/client/las.js/src/abr/abr-algorithm-simple.ts#L248

你好，这两个function看起来不太理解，能不能稍微解释下呢？

**Comment by johnwenjunwu** [comment]
_getPredictedBuffer：基于历史buffer和当前buffer，预测未来的buffer水平
_getBufferSpeed：基于buffer变化（数据下载增加buffer、播放消耗buffer），从而计算下载的速度

**Comment by wangynustc** [comment]
> _getPredictedBuffer：基于历史buffer和当前buffer，预测未来的buffer水平
> _getBufferSpeed：基于buffer变化（数据下载增加buffer、播放消耗buffer），从而计算下载的速度

含义很好理解，但我还是不太清楚这两个function为什么要这么算，似乎都是拿当前buffer值减去前一段时间最大的buffer值，不理解为什么要这么算？

**Comment by johnwenjunwu** [comment]
直播场景下，尤其是低延时模式下，希望能尽快恢复buffer，避免网络抖动或者码率抖动造成卡顿。选最大值，相当于基于过去的一步、两步、三步……，分别往后预测一步、两步、三步……后的最坏情况。
