### ISSUE TITLE
LAS have support edge server like http-flv in SRS

### ISSUE THREAD

**Issue by codecrack3** [KwaiVideoTeam/las#11]
I want to scaling my project using LAS. But i wonder how can i using edge server like http-flv

**Comment by johnwenjunwu** [comment]
Thanks for asking.

If you want to know how to support LAS on your edge server, follow this [commit](https://github.com/dean-river/srs/commit/65b7bc).

If you want to know how to use edge server, it's out of this project's scope.

**Comment by codecrack3** [comment]
Hi

Thank you for replying to me. I think I have an answer.
