### ISSUE TITLE
直接跑srs不成功

### ISSUE THREAD

**Issue by zhouxiang93123** [KwaiVideoTeam/las#2]
部署了srs然后把manifest.json的url改了报202-source buffer error错误，能不能把转码视频上传下，是不是codec有问题？
ffmpeg.exe  -re -i test.mp4 -vcodec libx264 -vf scale=1280:720 -b:v 2000k -x264-params "no-scenecut=1:threads=8:keyint=90" -acodec aac  -f flv rtmp://192.168.6.62:1935/live/out0 -vcodec libx264 -vf scale=960:540 -b:v 1000k -x264-params "no-scenecut=1:threads=8:keyint=90" -acodec aac  -f flv rtmp://192.168.6.62:1935/live/out1  -vcodec libx264 -vf scale=640:360 -b:v 500k -x264-params "no-scenecut=1:threads=8:keyint=90" -acodec aac  -f flv rtmp://192.168.6.62:1935/live/out2

**Comment by johnwenjunwu** [comment]
这个里面有三条流，拉下来试试？
https://github.com/KwaiVideoTeam/las/blob/master/client/las.js/demo/manifest.json

**Comment by zhouxiang93123** [comment]
用里面的流是可以的，我想自己搭建视频服务端，发现不行，是什么原因呢，能不能把in.flv给传上去

**Comment by zhouxiang93123** [comment]
> 这个里面有三条流，拉下来试试？
> https://github.com/KwaiVideoTeam/las/blob/master/client/las.js/demo/manifest.json

直接用原生的https://github.com/KwaiVideoTeam/las/blob/master/client/las.js/demo/manifest.json
是可以的，但是我自己搭建就不行，请问是什么原因呢

**Comment by johnwenjunwu** [comment]
可以直接`wget "https://las-tech.org.cn/kwai/las-test.flv"`，把2M的流拉下来，当作原始流推。
当然啦，我们的测试原始流也推上来了：
https://github.com/KwaiVideoTeam/las/blob/master/transcode/in.flv

**Comment by iamyunlong** [comment]
您好，我在本地运行了demo播放器，然后按照说明配置了SRS和推流，拉流的地址是什么呢？我用ttps://github.com/KwaiVideoTeam/las/blob/master/client/las.js/demo/manifest.json，这个地址，也不能成功播放。直接，播放rtmp://127.0.0.1/livestream/out0这个推流地址是可以的。

**Comment by johnwenjunwu** [comment]
> 您好，我在本地运行了demo播放器，然后按照说明配置了SRS和推流，拉流的地址是什么呢？我用ttps://github.com/KwaiVideoTeam/las/blob/master/client/las.js/demo/manifest.json，这个地址，也不能成功播放。直接，播放rtmp://127.0.0.1/livestream/out0这个推流地址是可以的。

这个地址可以播放吗？https://kwaivideoteam.github.io/las.js/demo/index.html
需要自己组合一个manifest.json，里面分别填上rtmp对应的http拉流地址

**Comment by zhouxiang93123** [comment]
> 您好，我在本地运行了demo播放器，然后按照说明配置了SRS和推流，拉流的地址是什么呢？我用ttps://github.com/KwaiVideoTeam/las/blob/master/client/las.js/demo/manifest.json，这个地址，也不能成功播放。直接，播放rtmp://127.0.0.1/livestream/out0这个推流地址是可以的。

如果是不同的机器的话，ip不能填127的，另外manifest.json里的url要对应修改的，建议好好看看文档，搞清楚每一个参数再动手搭建。

**Comment by linuxliu** [comment]
srs上面要启用 http flv
https://github.com/ossrs/srs/wiki/v3_CN_SampleHttpFlv
然后才能得到 rtmp对应的http flv的地址
http://xxxxx:8080/livestream/out0.flv,
然后替换地址mainfest 里面的url就可以了
还有client的js 浏览器支不支持的方法，并不是isSupported() 而是 isSupport

**Comment by chiachi17** [comment]
請問能以 SRS transcode 來部署转码？

**Comment by johnwenjunwu** [comment]
完全可以

**Comment by chiachi17** [comment]
若用 SRS 转多档码率是否會有 I 帧的 pts 不一致的問題？

**Comment by johnwenjunwu** [comment]
看看有没有类似的参数 no-scenecut=1，来确保 I 帧的 pts 对齐
