### ISSUE TITLE
和LHLS比较怎样？

### ISSUE THREAD

**Issue by dearplain** [KwaiVideoTeam/las#5]
感觉不如LHLS简洁，CDN厂商要支持las，改动太大。

**Comment by johnwenjunwu** [comment]
主流CDN厂商已经支持LAS标准：比如阿里、网宿、腾讯、金山、百度
CDN改动可参考😄：https://las-tech.org.cn/#/docs/las1.0/las_sd?id=_5-las服务描述

**Comment by zhouxiang93123** [comment]
> 感觉不如LHLS简洁，CDN厂商要支持las，改动太大。

lhls的时延还是瓶颈，LAS主打的应该还是低时延。毕竟是基于flv的帧级别的切换。

**Comment by zhouxiang93123** [comment]
> 感觉不如LHLS简洁，CDN厂商要支持las，改动太大。

lhls的时延还是瓶颈，LAS主打的应该还是低时延

**Comment by dearplain** [comment]
> > 感觉不如LHLS简洁，CDN厂商要支持las，改动太大。
> 
> lhls的时延还是瓶颈，LAS主打的应该还是低时延

lhls时延应该可以很低，先给你一个链接，有数据就吐给你，没什么延迟。还可以预先订阅，边缘节点也有时间进行回源。慢的也许是TCP。
